### ISSUE TITLE
Template travis.yml cache always changed

### ISSUE THREAD

**Issue by nallar** [mockito/shipkit#426]
The travis.yml shipkit sets up results in a cache which is always changed, slowing down builds.

Travis recommend [removing some files](https://docs.travis-ci.com/user/languages/java/#Caching), but this seems to be out of date too as it still resulted in changed on every build with gradle 4.2.

Copying the [cache section from this project](https://github.com/mockito/shipkit/blob/master/.travis.yml#L25) still didn't work.

Also removing SNAPSHOT dependencies and metadata-*/*.bin seems to work.

```yml
before_cache:
# SNAPSHOT dependency related files were being updated for every build even with no actual change to the dependency
  - find $HOME/.gradle/caches/modules-2 -name \*-SNAPSHOT -type d -exec rm -rf {} +
# these are changed every build and can't be cached
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -f  $HOME/.gradle/caches/modules-2/metadata-*/*.bin
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
  - rm -fr $HOME/.gradle/caches/*/scripts-remapped/
  - rm -fr $HOME/.gradle/caches/*/fileHashes/
  - rm -fr $HOME/.gradle/caches/transforms-1/transforms-1.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
```

The cache will also get bigger if the gradle wrapper version is changed. It'd be good to either automatically clear out older versions in that case somehow, or to add documentation recommending clearing the travis cache after changing the gradle version.
