### ISSUE TITLE
Instructions/compatibility with GitHub Actions

### ISSUE THREAD

**Issue by magneticflux-** [mockito/shipkit#842]
Now that GitHub Actions is in beta and more people are getting access to it, it makes sense to broaden the compatible CI environments for ShipKit.

**Comment by aepfli** [comment]
Just an fyi, we (https://github.com/junit-pioneer/junit-pioneer) migrated now from travis to github actions. it is working with some "hacks".

1. shipkit relies on the environment variable `TRAVIS_BRANCH` to work successfully, but this can be easily injected
2. `github.ref` which contains the branch contains it with `refs/head/` in the beginning, which cause troubles and needs to be split

our deploy action look like

``` yaml
deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy with Shipkit
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Sanitize Branch
        uses: frabert/replace-string-action@master
        id: gitbranch
        with:
          pattern: 'refs/heads/(.*)'
          string: "${{ github.ref }}"
          replace-with: '$1'
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Perform Release
        uses: eskatos/gradle-command-action@v1
        env:
          TRAVIS_BRANCH: ${{ steps.gitbranch.outputs.replaced }}
          GH_WRITE_TOKEN: ${{ secrets.GH_WRITE_TOKEN }}
          BINTRAY_USER_NAME: ${{ secrets.BINTRAY_USER_NAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          NEXUS_TOKEN_USERNAME: ${{ secrets.NEXUS_TOKEN_USERNAME }}
          NEXUS_TOKEN_PASSWORD: ${{ secrets.NEXUS_TOKEN_PASSWORD }}
        with:
          arguments: ciPerformRelease
```
and in our shipkit.gradle we added some parameters so that CI is correctly linked.
